services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongodb_data:/data/db

  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT:-3000}
    command: sh -c "/wait && cd /app/server && npx ts-node-dev -r tsconfig-paths/register --inspect=0.0.0.0:1339 -P ./tsconfig.json src/main.ts"
    environment:
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0
      - NODE_ENV
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SUBJECT=${EMAIL_SUBJECT}
      - MONGODB_URI=mongodb://mongodb:27017/control-yourself
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
    ports:
      - "${SERVER_PORT:-3000}:3000"
      - '1339:1339'
    volumes:
      - ./server:/app/server
    depends_on:
      - mongodb

  bot:
    platform: linux/amd64
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: sh -c "cd /app && npm run watch"
    environment:
      - NODE_ENV
      - BOT_TOKEN
      - API_URL=http://server:3000
    volumes:
      - ./bot:/app
    depends_on:
      - server