version: '3.8'

services:
  mock-services:
    build:
      context: ./mock-services
      dockerfile: Dockerfile
    ports:
      - "${MOCK_SERVICES_PORT:-3001}:3001"
    environment:
      - MOCKSERVER_PORT=3001
      - NODE_ENV=development
      - IMAP_HOST=mock-services
      - IMAP_PORT=1143
      - IMAP_USER=test@example.com
      - IMAP_PASSWORD=test123
      - IMAP_TLS=false
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SUBJECT=${EMAIL_SUBJECT}
    volumes:
      - ./mock-services:/app
      - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      - SERVER_PORT=3000
      - NODE_ENV=development
      - IMAP_HOST=mock-services
      - IMAP_PORT=1143
      - IMAP_USER=test@example.com
      - IMAP_PASSWORD=test123
      - IMAP_TLS=false
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SUBJECT=${EMAIL_SUBJECT}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mock-services

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://server:3000
    volumes:
      - ./bot:/app
      - /app/node_modules
    depends_on:
      - server 